server:
#服务器访问端口
  port: 8080
  tomcat:
    max-threads: 2000
    min-spare-threads: 10
#  session:
#    cookie:
#      http-only: true
spring:
  application:
    name: domaincheck
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #true则url、username、password必须进行加密，设置为false则不使用加密
    isencrypt: false
#    url: amRiYzpteXNxbDovLzE5Mi4xNjguMS4yMjE6MzMwNi9kaWNlP3VzZVVuaWNvZGU9dHJ1ZSZjaGFyYWN0ZXJFbmNvZGluZz11dGYtOA==
#    username: cm9vdA==
#    password: MTIzNDU2
    url: jdbc:mysql://127.0.0.1:3306/domain?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
    initial-size: 2
    max-active: 300
    min-idle: 2
    max-total: 350
    # 配置获取连接等待超时的时间
    max-wait-millis: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-open-prepared-statements: 200
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j

  thymeleaf:
      cache: false
      check-template-location: true
      content-type: text/html
      enabled: true
      encoding: utf-8
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html