package com.pk.domaincheck.domain.mapper;

import com.pk.domaincheck.domain.domain.Userinfo;
import org.apache.ibatis.jdbc.SQL;

public class UserinfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated
     */
    public String insertSelective(Userinfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("userinfo");
        
        if (record.getUserid() != null) {
            sql.VALUES("userid", "#{userid,jdbcType=INTEGER}");
        }
        
        if (record.getUsername() != null) {
            sql.VALUES("username", "#{username,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            sql.VALUES("sex", "#{sex,jdbcType=BIT}");
        }
        
        if (record.getTel() != null) {
            sql.VALUES("tel", "#{tel,jdbcType=VARCHAR}");
        }
        
        if (record.getLastlogintime() != null) {
            sql.VALUES("lastlogintime", "#{lastlogintime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=BIT}");
        }
        
        if (record.getWxopenid() != null) {
            sql.VALUES("wxopenid", "#{wxopenid,jdbcType=VARCHAR}");
        }
        
        if (record.getAddr() != null) {
            sql.VALUES("addr", "#{addr,jdbcType=VARCHAR}");
        }
        
        if (record.getDelStatus() != null) {
            sql.VALUES("del_status", "#{delStatus,jdbcType=BIT}");
        }
        
        if (record.getCreatetime() != null) {
            sql.VALUES("createtime", "#{createtime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Userinfo record) {
        SQL sql = new SQL();
        sql.UPDATE("userinfo");
        
        if (record.getUsername() != null) {
            sql.SET("username = #{username,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            sql.SET("sex = #{sex,jdbcType=BIT}");
        }
        
        if (record.getTel() != null) {
            sql.SET("tel = #{tel,jdbcType=VARCHAR}");
        }
        
        if (record.getLastlogintime() != null) {
            sql.SET("lastlogintime = #{lastlogintime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=BIT}");
        }
        
        if (record.getWxopenid() != null) {
            sql.SET("wxopenid = #{wxopenid,jdbcType=VARCHAR}");
        }
        
        if (record.getAddr() != null) {
            sql.SET("addr = #{addr,jdbcType=VARCHAR}");
        }
        
        if (record.getDelStatus() != null) {
            sql.SET("del_status = #{delStatus,jdbcType=BIT}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("createtime = #{createtime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("userid = #{userid,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}